[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "./contracts" },
    { access = "read", path = "lib/chainlink-brownie-contracts/contracts/src" },
    { access = "write", path = "./" },
    { access = "write", path = "./contracts" }
]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "chainlink/=lib/chainlink-brownie-contracts/contracts/src/",
    "@redstone-finance/evm-connector/=lib/redstone-oracles-monorepo/packages/evm-connector/"
]

[profile.default.rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }



